# Generated by Django 5.0.4 on 2024-04-30 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('lastname', models.CharField(max_length=500)),
                ('fname', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('school', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(max_length=3000)),
                ('JSHSHIR', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('userdate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('english', 'english'), ('others', 'others'), ('nemesis', 'nemesis')], max_length=300, verbose_name='Language')),
                ('overel', models.CharField(choices=[('C1', 'C1'), ('B2', 'B2')], max_length=2, verbose_name='Overel')),
                ('url', models.CharField(blank=True, max_length=300)),
                ('serticatedate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uqimoqda', 'uqimoqda'), ('tugatgan', 'tugatgan')], max_length=300)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='adduser.userinfo')),
            ],
        ),
    ]
