# Generated by Django 5.0.4 on 2024-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0002_alter_certificate_overel_alter_certificate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='overel',
            field=models.CharField(choices=[('C1', 'C1'), ('B2', 'B2')], max_length=2, verbose_name='Overel'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(choices=[('nemesis', 'nemesis'), ('english', 'english'), ('others', 'others')], max_length=300, verbose_name='Language'),
        ),
    ]
