# Generated by Django 5.0.4 on 2024-05-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0005_alter_certificate_overel_alter_certificate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='title',
            field=models.CharField(choices=[('english', 'english'), ('others', 'others'), ('nemesis', 'nemesis')], default='english', max_length=300, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
