# Generated by Django 5.0.4 on 2024-05-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0008_alter_certificate_overel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(choices=[('others', 'others'), ('nemesis', 'nemesis'), ('english', 'english')], max_length=300, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='title',
            field=models.CharField(choices=[('others', 'others'), ('nemesis', 'nemesis'), ('english', 'english')], max_length=300, verbose_name='Language'),
        ),
    ]
