# Generated by Django 5.0.4 on 2024-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0010_alter_certificate_title_alter_userinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='overel',
            field=models.CharField(choices=[('B2', 'B2'), ('C1', 'C1')], max_length=2, verbose_name='Overel'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(choices=[('nemesis', 'nemesis'), ('others', 'others'), ('english', 'english')], max_length=300, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='title',
            field=models.CharField(choices=[('nemesis', 'nemesis'), ('others', 'others'), ('english', 'english')], max_length=300, verbose_name='Language'),
        ),
    ]
