# Generated by Django 5.0.4 on 2024-05-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0012_alter_certificate_title_alter_userinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(choices=[('english', 'english'), ('nemesis', 'nemesis'), ('others', 'others')], max_length=300, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='title',
            field=models.CharField(choices=[('english', 'english'), ('nemesis', 'nemesis'), ('others', 'others')], max_length=300, verbose_name='Language'),
        ),
    ]
