# Generated by Django 5.0.4 on 2024-05-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adduser", "0041_alter_certificate_title_alter_userinfo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="title",
            field=models.CharField(
                choices=[
                    ("others", "others"),
                    ("english", "english"),
                    ("nemesis", "nemesis"),
                ],
                max_length=300,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="title",
            field=models.CharField(
                choices=[
                    ("others", "others"),
                    ("english", "english"),
                    ("nemesis", "nemesis"),
                ],
                max_length=300,
                verbose_name="Language",
            ),
        ),
    ]
