# Generated by Django 5.0 on 2024-05-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0064_alter_certificate_overel_alter_certificate_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='overel',
            field=models.CharField(choices=[('B2', 'B2'), ('C1', 'C1')], max_length=2, verbose_name='Overel'),
        ),
    ]
